#ifndef _ERROR_H
#define _ERROR_H

#define ERR_SAME_NODE 1
#define ERR_NODE_NOT_FOUND 2
#define ERR_FN_POINTER_NULL 3
#define ERR_NODE_ADD_NULL 4
#define ERR_HEIGHT_INC_DEC_NULL 5
#define ERR_DELETE_VALUE_NULL 6
#endif // _EXCEPTION_H
